### ISSUE TITLE
More dependencies on installation

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/readdst#33] opened 2017-01-26 14:18 UTC
Performing an `install_github()`, I've had install failures because 
* `Formula` not found
* `acepack` not found
* `latticeExtra` not found
* `htmltable` not found  - which installs `checkmate`

hooray, only 4 failed installation attempts

**Comment by dill** [comment] 2017-01-26 14:34
This is very strange, none of these are dependencies for readdst, and I've actually not heard of most of them.

I installed from github (no problem) loaded `readdst` and, indeed, they are loaded

```
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X Yosemite 10.10.5

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] readdst_0.0.3

loaded via a namespace (and not attached):
 [1] splines_3.3.2       lattice_0.20-34     colorspace_1.3-2
 [4] testthat_1.0.2      htmltools_0.3.5     mgcv_1.8-16
 [7] base64enc_0.1-3     survival_2.40-1     foreign_0.8-67
[10] RColorBrewer_1.1-2  optimx_2013.8.7     plyr_1.8.4
[13] stringr_1.1.0       munsell_0.4.3       dfoptim_2016.7-1
[16] gtable_0.2.0        setRNG_2013.9-1     latticeExtra_0.6-28
[19] Rvmmin_2013-11.12   knitr_1.15.1        parallel_3.3.2
[22] htmlTable_1.8       Rcpp_0.12.9         acepack_1.4.1
[25] readr_1.0.0         backports_1.0.5     scales_0.4.1
[28] checkmate_1.8.2     Hmisc_4.0-2         truncnorm_1.0-7
[31] gridExtra_2.2.1     BB_2014.10-1        ggplot2_2.2.1
[34] digest_0.6.11       svUnit_0.7-12       stringi_1.1.2
[37] numDeriv_2016.8-1   grid_3.3.2          quadprog_1.5-5
[40] mrds_2.1.17         tools_3.3.2         magrittr_1.5
[43] lazyeval_0.2.0      Rsolnp_1.16         tibble_1.2
[46] Formula_1.2-1       cluster_2.0.5       ucminf_1.1-4
[49] optextras_2016-8.8  crayon_1.3.2        RODBC_1.3-14
[52] Matrix_1.2-8        data.table_1.10.0   Rcgmin_2013-2.21
[55] assertthat_0.1      minqa_1.2.4         R6_2.2.0
[58] rpart_4.1-10        nnet_7.3-12         nlme_3.1-129
```

`readdst` has the following `Imports`: `Hmisc`, `stringr`, `magrittr`, `mrds`, `testthat`, `plyr`, `readr`.

Using:

```
pkg <- lapply(c("Hmisc", "stringr", "magrittr", "mrds", "testthat", "plyr", "readr"), tools::package_dependencies)
```

It looks like `Hmisc` is the culprit -- do you have this package installed? (Maybe an old version?)

I also wonder if you have an older version of `devtools`, as I thought it now automatically downloaded dependencies...

**Comment by erex** [comment] 2017-01-26 14:36
**Entire universe behaving unusually**
```
> devtools::install_github("DistanceDevelopment/readdst")
Downloading GitHub repo DistanceDevelopment/readdst@master
from URL https://api.github.com/repos/DistanceDevelopment/readdst/zipball/master
Installing readdst
Installing 1 package: Hmisc
Installing package into ‘C:/Users/eric/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/Hmisc_4.0-2.zip'
Content type 'application/zip' length 1785511 bytes (1.7 MB)
downloaded 1.7 MB

package ‘Hmisc’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\eric\AppData\Local\Temp\RtmpS4Ytdx\downloaded_packages
"C:/PROGRA~1/R/R-33~1.2/bin/i386/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  INSTALL  \
  "C:/Users/eric/AppData/Local/Temp/RtmpS4Ytdx/devtools22fc6dbd2af5/DistanceDevelopment-readdst-c809543"  \
  --library="C:/Users/eric/Documents/R/win-library/3.3" --install-tests 

* installing *source* package 'readdst' ...
** R
** inst
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'Formula'
ERROR: lazy loading failed for package 'readdst'
* removing 'C:/Users/eric/Documents/R/win-library/3.3/readdst'
Error: Command failed (1)
> 
> install.packages("Formula")
Installing package into ‘C:/Users/eric/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/Formula_1.2-1.zip'
Content type 'application/zip' length 163536 bytes (159 KB)
downloaded 159 KB

package ‘Formula’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\eric\AppData\Local\Temp\RtmpS4Ytdx\downloaded_packages
> devtools::install_github("DistanceDevelopment/readdst")
Downloading GitHub repo DistanceDevelopment/readdst@master
from URL https://api.github.com/repos/DistanceDevelopment/readdst/zipball/master
Installing readdst
"C:/PROGRA~1/R/R-33~1.2/bin/i386/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  INSTALL  \
  "C:/Users/eric/AppData/Local/Temp/RtmpS4Ytdx/devtools22fc3ef57931/DistanceDevelopment-readdst-c809543"  \
  --library="C:/Users/eric/Documents/R/win-library/3.3" --install-tests 

* installing *source* package 'readdst' ...
** R
** inst
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'acepack'
ERROR: lazy loading failed for package 'readdst'
* removing 'C:/Users/eric/Documents/R/win-library/3.3/readdst'
Error: Command failed (1)
> install.packages("acepack")
Installing package into ‘C:/Users/eric/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/acepack_1.4.1.zip'
Content type 'application/zip' length 90516 bytes (88 KB)
downloaded 88 KB

package ‘acepack’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\eric\AppData\Local\Temp\RtmpS4Ytdx\downloaded_packages
> devtools::install_github("DistanceDevelopment/readdst")
Downloading GitHub repo DistanceDevelopment/readdst@master
from URL https://api.github.com/repos/DistanceDevelopment/readdst/zipball/master
Installing readdst
"C:/PROGRA~1/R/R-33~1.2/bin/i386/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  INSTALL  \
  "C:/Users/eric/AppData/Local/Temp/RtmpS4Ytdx/devtools22fc41611e38/DistanceDevelopment-readdst-c809543"  \
  --library="C:/Users/eric/Documents/R/win-library/3.3" --install-tests 

* installing *source* package 'readdst' ...
** R
** inst
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'latticeExtra'
ERROR: lazy loading failed for package 'readdst'
* removing 'C:/Users/eric/Documents/R/win-library/3.3/readdst'
Error: Command failed (1)
> install.packages("latticeExtra")
Installing package into ‘C:/Users/eric/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/latticeExtra_0.6-28.zip'
Content type 'application/zip' length 2069509 bytes (2.0 MB)
downloaded 2.0 MB

package ‘latticeExtra’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\eric\AppData\Local\Temp\RtmpS4Ytdx\downloaded_packages
> devtools::install_github("DistanceDevelopment/readdst")
Downloading GitHub repo DistanceDevelopment/readdst@master
from URL https://api.github.com/repos/DistanceDevelopment/readdst/zipball/master
Installing readdst
"C:/PROGRA~1/R/R-33~1.2/bin/i386/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  INSTALL  \
  "C:/Users/eric/AppData/Local/Temp/RtmpS4Ytdx/devtools22fc656a7852/DistanceDevelopment-readdst-c809543"  \
  --library="C:/Users/eric/Documents/R/win-library/3.3" --install-tests 

* installing *source* package 'readdst' ...
** R
** inst
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'htmlTable'
ERROR: lazy loading failed for package 'readdst'
* removing 'C:/Users/eric/Documents/R/win-library/3.3/readdst'
Error: Command failed (1)
> install.packages("htmlTable")
Installing package into ‘C:/Users/eric/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
also installing the dependency ‘checkmate’

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/checkmate_1.8.2.zip'
Content type 'application/zip' length 554623 bytes (541 KB)
downloaded 541 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/htmlTable_1.8.zip'
Content type 'application/zip' length 179256 bytes (175 KB)
downloaded 175 KB

package ‘checkmate’ successfully unpacked and MD5 sums checked
package ‘htmlTable’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\eric\AppData\Local\Temp\RtmpS4Ytdx\downloaded_packages
> devtools::install_github("DistanceDevelopment/readdst")
Downloading GitHub repo DistanceDevelopment/readdst@master
from URL https://api.github.com/repos/DistanceDevelopment/readdst/zipball/master
Installing readdst
"C:/PROGRA~1/R/R-33~1.2/bin/i386/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  INSTALL  \
  "C:/Users/eric/AppData/Local/Temp/RtmpS4Ytdx/devtools22fc68559f5/DistanceDevelopment-readdst-c809543"  \
  --library="C:/Users/eric/Documents/R/win-library/3.3" --install-tests 

* installing *source* package 'readdst' ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (readdst)
```

**Comment by dill** [comment] 2017-01-26 14:46
"Fixed" ?

**Comment by erex** [comment] 2017-01-26 14:50
umm, readdst is now installed, but won't swallow this terrible murrelet dataset with "MCDS strata mismatch error"--the same dataset causing D7 to produce "% component of variation" of 114%.  Essentially everything I've touched today is gubbed.

**Comment by dill** [comment] 2017-01-26 14:51
ack. Do you want to e-mail me the murrelet data and I can take a look?

**Comment by erex** [comment] 2017-01-26 14:52
If I got to choose my battles, I'd rather have the minke data give me a consistent answer from `ds()` for my students (they are nearer)

**Comment by dill** [comment] 2017-01-26 14:55
looking at that now... but out from 10-12 EST, so don't expect anything 
soon...

**Comment by erex** [comment] 2017-01-26 15:02
Thanks Dave.  More fuel for the minke fire.  I ran the minke data through D7, getting a result that matches my "first principles result" and not the `ds()` result:

```
Effort        :    1842.790    
 # samples     :    25
 Width         :    1.940000    
 # observations:    90

 Model
    Half-normal key, k(y) = Exp(-y**2/(2*A(1)**2))


              Point        Standard    Percent Coef.        95% Percent
  Parameter   Estimate       Error      of Variation     Confidence Interval
  ---------  -----------  -----------  --------------  ----------------------
    D        0.27851E-01  0.70620E-02      25.36      0.16715E-01  0.46404E-01
    N         19922.       5051.5          25.36       11957.       33194.    
  ---------  -----------  -----------  --------------  ----------------------

 Measurement Units                
 ---------------------------------
 Density: Numbers/Sq. nautical mi
     ESW: nautical miles 

 Component Percentages of Var(D)
 -------------------------------
 Detection probability   :   9.2
 Encounter rate          :  90.8
```

**Comment by erex** [comment] 2017-01-26 20:14
True, this has resolved the `Distance` issue, but not the `readdst` installation story, hence I reopen.

**Comment by dill** [comment] 2018-05-25 15:01
Coming back to this now -- what's the story now? Are you able to reproduce this error?

**Comment by erex** [comment] 2018-05-29 08:27
a comment on package dependency, not about the minke data.

Installing readdst 0.0.5 brings this message:
```
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'data.table'
ERROR: lazy loading failed for package 'readdst'
* removing 'C:/Users/eric/Documents/R/win-library/3.5/readdst'
* restoring previous 'C:/Users/eric/Documents/R/win-library/3.5/readdst'
```

I'm guessing `data.table` needs to be added to the dependency in the package description?

**Comment by dill** [comment] 2018-05-30 07:15
It appears this is a new dependency for `Hmisc`:

```
> tools::package_dependencies("Hmisc")
$Hmisc
 [1] "lattice"      "survival"     "Formula"      "ggplot2"      "methods"
 [6] "latticeExtra" "cluster"      "rpart"        "nnet"         "acepack"
[11] "foreign"      "gtable"       "grid"         "gridExtra"    "data.table"
[16] "htmlTable"    "viridis"      "htmltools"    "base64enc"
```

running `update.packages()` on your machine should clear this issue.

**Comment by dill** [comment] 2018-05-30 07:17
Going to close this as it looks like this has meandered a lot since it was opened. I believe we fixed the minke issue and the remaining thing is murrelets but I have no recollection of that problem. If that's outstanding can you start a new murrelet issue?

**Closed as completed by dill** 2018-05-30 07:17 UTC

**Comment by erex** [comment] 2018-05-30 08:17
I've completely forgotten whose murrelet data this was.  issue dropped
